<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WrightLogs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\examples\simple\Decisions.Web.Core.log" Link="Fixtures\Decisions.Web.Core.log" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\examples\simple\Decisions.Web.Core.1.log" Link="Fixtures\Decisions.Web.Core.1.log" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\examples\simple\Decisions.Web.Core.Usage.csv" Link="Fixtures\Decisions.Web.Core.Usage.csv" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\examples\simple\Decisions.Web.Core.Usage.1.csv" Link="Fixtures\Decisions.Web.Core.Usage.1.csv" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>